# Generated by Django 5.1.5 on 2025-02-03 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name Topics')),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of the news')),
                ('content', models.TextField(verbose_name='Content of news')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Public date')),
                ('editors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Editors')),
                ('topics', models.ManyToManyField(blank=True, to='news.topic', verbose_name='Topics')),
            ],
        ),
    ]
